[package]
name = "bisky"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
bytemuck = "1.13.1"
egui = "0.22.0"
egui-wgpu = "0.22.0"
egui-winit = "0.22.0"
env_logger = "0.10.0"
log = "0.4.17"
pollster = "0.3.0"
tobj = "4.0.0"
wgpu = "0.16.1"
winit = "0.28.6"
